# Generated by Django 2.0.1 on 2019-10-20 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyed_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('user_email', models.CharField(max_length=25)),
                ('cost_product', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='product_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
                ('product', models.CharField(max_length=25)),
                ('cost', models.CharField(max_length=25)),
                ('noofproducts', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('phone_no', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('account_bln', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='buyer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_field'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_field'),
        ),
    ]
