# Generated by Django 2.0.1 on 2019-10-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buyed_field',
        ),
        migrations.RemoveField(
            model_name='product_field',
            name='product',
        ),
        migrations.AlterField(
            model_name='product_field',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
